### ISSUE TITLE
Sourcemaps?

### ISSUE THREAD

**Issue by roowilliams** [mscharley/jekyll-compass#31]
Hello,

I'm trying to use compass sourcemap output with this. As far as I understand I just need to add the `sourcemap: true` option to `compass.yml`.

With that done when generating I get:

```
Generating Compass: /home/roo/Development/roowilliams/_compass => /home/roo/Development/roowilliams/_site/css
write _site/css/screen.css
write _site/css/screen.css.map

Generating... ...done in 4.203803427 seconds.
```

The problem here is that it doesn't actually write the screen.css.map file, but it does write the sourcemap ref line to the css file which results in a 404 error for the sourcemap in Chrome Dev Tools. It also takes a lot longer than usual to generate

With `sourcemap: false`

```
Generating Compass: /home/roo/Development/roowilliams/_compass => /home/roo/Development/roowilliams/_site/css

Generating... ...done in 0.37714261 seconds.
```

Any suggestions?

Thanks

- Roo

**Comment by mscharley** [comment]
Not sure. Inclined to say this isn't something on my side and perhaps you should refer the question to the Compass devs. jekyll-compass doesn't interfere with Compass' generation of files at all, it just passes configuration through to the normal build process. I know for a fact that jekyll-compass works with other things that generate extra files (image spriting).

The one case I can think of that might cause this on our side if Compass doesn't raise any of the normal events for the map files. That would mean that jekyll-compass can't pass through to jekyll that these map files are supposed to exist and jekyll will wipe them out during it's build phase - generators like jekyll-compass run before the rest of the normal site build. This is arguably still a compass issue, so I'd definitely contact them and refer them to this bug report.

**Comment by roowilliams** [comment]
OK thanks for your reply Matt! I'll do as you recommend and post back with
the outcome.

Thanks again
